# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "android/**"
    - "ios/**"
    - "web/**"
    - "windows/**"
    - "macos/**"
    - "linux/**"
    - "node_modules/**"
    - "portal_web/**"
    - ".artifacts/**"
    - ".dart_tool/**"

  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    use_build_context_synchronously: ignore
    avoid_web_libraries_in_flutter: ignore
    unnecessary_underscores: ignore
    prefer_final_fields: ignore
    no_leading_underscores_for_local_identifiers: ignore
    use_null_aware_elements: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    unused_import: ignore

linter:
  rules:
    avoid_print: false
